version: '3.8'

services:
  web:
    build:
      context: frontend
      dockerfile: Dockerfile
    container_name: web
    restart: always
    depends_on:
      - 'api'
    ports:
      - "80:8080"
    networks:
      frontend:
  api:
    build:
      context: backend
      dockerfile: Dockerfile
    container_name: api
    restart: always
    depends_on:
      - 'db'
    ports:
      - "5000:5000"
    networks:
      backend:
        ipv4_address: 1.0.0.3
      frontend:
  db:
    image: postgres:latest
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      backend:
        ipv4_address: 1.0.0.2

volumes:
  db-data:

networks:
  backend:
    driver: bridge
    ipam:
      config:
        - subnet: 1.0.0.0/29
          gateway: 1.0.0.1
  frontend:
    driver: bridge
